---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
      annotations:
        networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-1
    spec:
      containers:
      - name: alpine
        image: alpine:3.15.0
        imagePullPolicy: IfNotPresent
        # simple `sleep` command would work
        # but we need `trap` to be able to delete pods quckly
        command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
