---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CIDR_PREFIX
              value: 172.16.1.1/24
            - name: NSM_SERVICE_NAMES
              value: "kernel2ethernet2kernel"
            - name: NSM_REGISTER_SERVICE
              value: "false"
